/*
Database Title: Football league Database

MEMBER DETAILS:
1. SHIKHAR DUBEY 201601144
2. VEDANT GUPTA 201601145
3. DARSHAN KAPADIYA 201601179
4. SUJIT CHAUHAN 201601180 

Content : DDL script of database
*/
CREATE SCHEMA FBL;
SET SEARCH_PATH TO FBL;
--CREATE TABLE TEAM(
--	TEAM_NAME VARCHAR(50) PRIMARY KEY,
--	VENUE_NAME VARCHAR(50) NOT NULL
--);
CREATE TABLE TEAM(
	TEAM_NAME VARCHAR(50) PRIMARY KEY,
	MATCHES_PLAYED SMALLINT NOT NULL,
	WON SMALLINT NOT NULL,
	DRAW SMALLINT NOT NULL,
	LOST SMALLINT NOT NULL,
	GOAL_FOR SMALLINT NOT NULL,
	GOAL_AGAINST SMALLINT NOT NULL,
	POINTS INT NOT NULL
);

CREATE TABLE CONTACT_DETAIL(
	TEAM_NAME VARCHAR(50),
	EMAIL VARCHAR(50) PRIMARY KEY,
	CONTACT_NO VARCHAR(20)
);

CREATE TABLE VENUE(
	TEAM_NAME VARCHAR(50) NOT NULL,
	VENUE_NAME VARCHAR(50) PRIMARY KEY,
	CAPACITY INT NOT NULL,
	CITY VARCHAR(50) NOT NULL
);
CREATE TABLE COACH(
	TEAM_NAME VARCHAR(50) NOT NULL,
	NAME VARCHAR(50) PRIMARY KEY
);
CREATE TABLE MANAGER(
	TEAM_NAME VARCHAR(50) NOT NULL,
	NAME VARCHAR(50) PRIMARY KEY
);


CREATE TABLE MATCHES(
	MATCH_NUMBER INT PRIMARY KEY,
	MATCH_DATE VARCHAR(10) NOT NULL,
	HOME_TEAM VARCHAR(50) NOT NULL,
	AWAY_TEAM VARCHAR(50) NOT NULL CHECK(HOME_TEAM <> AWAY_TEAM),
	REFEREE VARCHAR(50),
	SCORE_H SMALLINT NOT NULL,
	SCORE_A SMALLINT NOT NULL,
	MOM VARCHAR(20) NOT NULL
);
CREATE VIEW MATCH AS 
	SELECT MATCH_NUMBER,MATCH_DATE,HOME_TEAM,AWAY_TEAM,SCORE_H,SCORE_A,MOM FROM MATCHES;
CREATE TYPE GS AS ENUM('NT', 'ST');
CREATE TYPE GT AS ENUM('N', 'O', 'P');

CREATE TABLE GOALS(
	GOAL_ID INT PRIMARY KEY,
	GOAL_TIME INT NOT NULL,
	GOAL_TYPE GT NOT NULL,
	GOAL_SCHEDULE GS NOT NULL,
	GOAL_HALF SMALLINT CHECK ( GOAL_HALF >=1 AND GOAL_HALF <= 2) NOT NULL,
	ASSISTED_BY INT,
	MATCH_NUMBER INT NOT NULL,
	SCORED_BY INT NOT NULL
);

CREATE TYPE RT AS ENUM('MAIN', 'ASSISTANT');
CREATE TABLE HAS_REFEREE(
	MATCH_NUMBER INT NOT NULL,
	REF_LICENCE_NUMBER VARCHAR(8) NOT NULL,
	REF_TYPE  RT,
	PRIMARY KEY(MATCH_NUMBER, REF_LICENCE_NUMBER)
);

CREATE TABLE REFEREE(
	NAME VARCHAR(20) NOT NULL,
	REF_LICENCE_NUMBER VARCHAR(8) PRIMARY KEY
);

CREATE TABLE PLAYER(
	PLAYER_ID INT PRIMARY KEY,
	PLAYER_NAME VARCHAR(50) NOT NULL,
	TEAM_NAME VARCHAR(50) NOT NULL,
	AGE INT NOT NULL,
	NATIONALITY VARCHAR(20) NOT NULL,
	JERSEY_NO SMALLINT NOT NULL
);

CREATE TABLE CAPTAIN(
	TEAM_NAME VARCHAR(50) NOT NULL,
	PLAYER_ID INT,
	START_DATE VARCHAR(10) NOT NULL,
	END_DATE VARCHAR(10),
	PRIMARY KEY(PLAYER_ID, TEAM_NAME)
);
CREATE TYPE PO AS ENUM('CB', 'LB','RB','RW','LW','CF','SS','LM','RM','CM','AM','DM','GK');
CREATE TABLE POSITION(
	PID PO PRIMARY KEY,
	DISCRIPTION VARCHAR(20) 
);

CREATE TABLE PLAYS_ON(
	PLAYER_ID INT,
	PID PO,
	PRIMARY KEY(PLAYER_ID, PID)
);

CREATE TYPE BT AS ENUM('YELLOW', 'RED');
CREATE TABLE BOOKING(
	MATCH_NUMBER INT NOT NULL,
	PLAYER_ID INT NOT NULL,
	BOOKING_TIME INT NOT NULL,
	PLAY_SCHEDULE GS NOT NULL,
	BOOKING_TYPE BT NOT NULL,
	PRIMARY KEY(MATCH_NUMBER,PLAYER_ID)
);



CREATE TABLE SUBSTITUTION(
	MATCH_NUMBER INT NOT NULL,
	PLAYER_ID_OUT INT NOT NULL,
	PLAYER_ID_IN INT NOT NULL,
	PLAY_SCHEDULE GS NOT NULL,
	TIME_IN_OUT INT NOT NULL,
	PRIMARY KEY(PLAYER_ID_IN ,PLAYER_ID_OUT,MATCH_NUMBER)
);

--ALTER TABLE POINT_TABLE
--ADD FOREIGN KEY (TEAM_NAME) REFERENCES TEAM(TEAM_NAME);

ALTER TABLE CAPTAIN
ADD FOREIGN KEY (TEAM_NAME) REFERENCES TEAM(TEAM_NAME);

ALTER TABLE VENUE
ADD FOREIGN KEY (TEAM_NAME) REFERENCES TEAM(TEAM_NAME);

ALTER TABLE MATCHES
ADD FOREIGN KEY (HOME_TEAM) REFERENCES TEAM(TEAM_NAME);

ALTER TABLE MATCHES
ADD FOREIGN KEY (AWAY_TEAM) REFERENCES TEAM(TEAM_NAME);

ALTER TABLE COACH
ADD FOREIGN KEY (TEAM_NAME) REFERENCES TEAM(TEAM_NAME);

ALTER TABLE MANAGER
ADD FOREIGN KEY (TEAM_NAME) REFERENCES TEAM(TEAM_NAME);

ALTER TABLE PLAYER
ADD FOREIGN KEY (TEAM_NAME) REFERENCES TEAM(TEAM_NAME);

ALTER TABLE HAS_REFEREE
ADD FOREIGN KEY (MATCH_NUMBER) REFERENCES MATCHES(MATCH_NUMBER);

ALTER TABLE GOALS
ADD FOREIGN KEY (MATCH_NUMBER) REFERENCES MATCHES(MATCH_NUMBER);

ALTER TABLE CONTACT_DETAIL
ADD FOREIGN KEY (TEAM_NAME) REFERENCES TEAM(TEAM_NAME);

ALTER TABLE GOALS
ADD FOREIGN KEY (ASSISTED_BY) REFERENCES PLAYER(PLAYER_ID);

ALTER TABLE CAPTAIN
ADD FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYER_ID);

ALTER TABLE GOALS
ADD FOREIGN KEY (SCORED_BY) REFERENCES PLAYER(PLAYER_ID);

ALTER TABLE PLAYS_ON
ADD FOREIGN KEY (PID) REFERENCES POSITION(PID);

ALTER TABLE PLAYS_ON
ADD FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYER_ID);

ALTER TABLE HAS_REFEREE
ADD FOREIGN KEY (REF_LICENCE_NUMBER) REFERENCES REFEREE(REF_LICENCE_NUMBER);

ALTER TABLE SUBSTITUTION
ADD FOREIGN KEY (PLAYER_ID_IN) REFERENCES PLAYER(PLAYER_ID);

ALTER TABLE SUBSTITUTION
ADD FOREIGN KEY (PLAYER_ID_OUT) REFERENCES PLAYER(PLAYER_ID);

ALTER TABLE SUBSTITUTION
ADD FOREIGN KEY (MATCH_NUMBER) REFERENCES MATCHES(MATCH_NUMBER);

ALTER TABLE BOOKING
ADD FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYER_ID);

ALTER TABLE BOOKING
ADD FOREIGN KEY (MATCH_NUMBER) REFERENCES MATCHES(MATCH_NUMBER);